# Generated by Django 2.0.3 on 2018-03-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
