# Generated by Django 2.0.2 on 2018-03-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodfinder', '0002_request_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='has_accepted',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='donations',
            name='has_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smsbuffer',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
