# Generated by Django 2.0.2 on 2018-03-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodfinder', '0003_auto_20180317_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='has_accepted',
            new_name='is_accepted',
        ),
        migrations.RenameField(
            model_name='donations',
            old_name='has_completed',
            new_name='is_completed',
        ),
    ]
